# Generated by Django 3.2 on 2021-04-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi_range', models.CharField(max_length=15)),
                ('suggestions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
