# Generated by Django 3.2 on 2021-04-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMIcalcapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestions',
            name='bmi_range',
        ),
        migrations.AddField(
            model_name='suggestions',
            name='higher_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestions',
            name='lower_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestions',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
