# Generated by Django 3.2 on 2021-04-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0011_rename_suggestions_usermodel_state'),
        ('BMIcalcapp', '0002_auto_20210429_2216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suggestions',
            new_name='State',
        ),
    ]
