# Generated by Django 3.2 on 2021-05-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMIcalcapp', '0004_auto_20210430_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
