# Generated by Django 3.2 on 2021-04-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
    ]
