# Generated by Django 3.2 on 2021-04-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_usermodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
