# Generated by Django 3.2 on 2021-04-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_usermodel_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
