# Generated by Django 3.2 on 2021-04-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_alter_usermodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
