# Generated by Django 3.2 on 2021-04-22 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_alter_usermodel_age'),
        ('useraccount', '0005_auto_20210420_0842'),
    ]

    operations = [
    ]
