# Generated by Django 3.2 on 2021-04-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_merge_20210422_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
