# Generated by Django 3.2 on 2021-04-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0007_auto_20210422_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='age',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
