# Generated by Django 3.2 on 2021-04-24 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0008_alter_usermodel_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='email_confirmed',
        ),
    ]
