# Generated by Django 3.2 on 2021-04-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BMIcalcapp', '0001_initial'),
        ('useraccount', '0009_remove_usermodel_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='suggestions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BMIcalcapp.suggestions'),
        ),
    ]
