# Generated by Django 3.2 on 2021-04-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0010_usermodel_suggestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='suggestions',
            new_name='state',
        ),
    ]
