# Generated by Django 3.2 on 2021-05-05 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0011_rename_suggestions_usermodel_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='name',
        ),
    ]
